puts "It is a very serious crime to pirate OS-GH."
puts "You have violated the OS-GH License terms."
puts "The OS-GH Team and your local authorities have been notified of this action and your location has been sent to them."
puts "We or they will sue or otherwise arrest you."
puts "To continue, you must install a legal version of OS-GH provided by the OS-GH Team."
puts "Your computer has been locked due to this illegal action."
puts "Thanks for using OS-GH."
puts "SHUT DOWN AND REPORT NOW!"
puts ""
puts "Press E to dial 911 and report to emergency services. Press Enter to download and install a fresh legit copy of OS-GH. Press any other button to turn off your OS-GH computer."
